### ISSUE TITLE
Better developer experience in views and more predictable styling

### ISSUE THREAD

**Issue by ochmanski** [odziminski/garden#1]
## The problem

You don't specifically know how e.g. line break would occur because you're using random 10 chars as a name for a `Plant` or `User`. Plants and users could have much longer names so there could be a situation when your styling breaks, because you've been used to styling your components based on 10 random characters.

## Possible solution

Please take a look at [Database testing](https://laravel.com/docs/7.x/database-testing#writing-factories). Maybe make a dictionary with - let's say - 20 plants' names and use them throughout the seeder services?

## Files

https://github.com/odziminski/garden/blob/7420135ec391f6c62ab2f761f48e121a680ee3b5/database/seeders/PlantsSeeder.php#L21

https://github.com/odziminski/garden/blob/7420135ec391f6c62ab2f761f48e121a680ee3b5/database/seeders/UserSeeder.php#L21

and other fields that depend on `Str::random`

**Comment by odziminski** [comment]
Seems interesting, I'm gonna take a look at that.

**Comment by odziminski** [comment]
Fixed by creating a 15-element array of sample plants and a function to pick and return one of them randomly.

` public function getRandomPlantName(){
        $samplePlants = [
            'Aloe',
            'Peace lily',
            'Mother-in-law’s Tongue',
            'Zanzibar Gem',
            'Maidenhair',
            'Rubber Plant',
            'Begonia',
            'Belladonna Lily',
            'Eternal flame',
            'Beach Spider Lily',
            'African Violet',
            'Queens Tears',
            'Madagascar Jasmine',
            'Moth Orchid',
            'Winter Cherry'
        ];
        $random = Arr::random($samplePlants);
        return $random;
    }`

` 'name' => self::getRandomPlantName(), `
